### ISSUE TITLE
Criar View Novo Evento

### ISSUE THREAD

**Issue by maykealisson** [MaykeAlisson/novoanjo#2]
Modelo: Deve conter um formulário onde a pessoa que deseja cadastrar um novo evento deve informar seu nome, email e preencher um formulário com as informações referente ao evento, como data, hora, local, responsável e telefone, e a modalidade que necessita como tempo, serviço, mantimentos...
exemplos:

**Comment by xavierleonardo** [comment]
@MaykeAlisson, gostaria de ajudar nesta issue. Como posso proceder?

**Comment by maykealisson** [comment]
@xavierleonardo trata-se de um formulário para cadastrar novo evento como descrito no resumo da issue, estamos usando a engine ejs para o nodejs então a view deve ser um .ejs. Estamos usando também o bootstrap se achar mais confortável. Fique a vontade para criar o formulário da forma que achar mais interessante. Se quiser da uma olhada no branch develop, com ele da para ter uma boa noção de como estamos trabalhando. Qualquer coisa e só perguntar .

**Comment by xavierleonardo** [comment]
Obrigado, @MaykeAlisson. Minha dúvida era mais com relação ao procedimento mesmo. Eu já dei uma olhada na aplicação e não encontrei um banco de dados ou algum lugar pra guardar essa informação. Posso assumir essa issue como apenas o template, ficando a funcionalidade para outra issue?

**Comment by maykealisson** [comment]
@xavierleonardo Isso mesmo vamos criar todo o front end primeiro, para ai sim desenvolvermos todo o back end. Esta issue trata-se somente do template mesmo.

**Comment by xavierleonardo** [comment]
@MaykeAlisson, procurei deixar a _branch_, os _commits_ e a descrição da _Pull Request_ bem detalhados, mas resumindo o que eu fiz:

- Criei o template da página `novo-evento.ejs`
- Criei as rotas de _get_ e _post_ para esta funcionalidade
- Adicionei o _body-parser_ pra pegar os dados da requisição em formato de objeto _JavaScript_

#8

**Comment by maykealisson** [comment]
@xavierleonardo Muito obrigado pela contribuição, e parabéns pela organização.
Muito obrigado mesmo pela ajuda.

**Comment by xavierleonardo** [comment]
> @xavierleonardo Muito obrigado pela contribuição, e parabéns pela organização.
> Muito obrigado mesmo pela ajuda.

Por nada, @MaykeAlisson. Já estou pensando na próxima, hehehehe.

De qualquer maneira, apesar de você já ter fechado a _issue_, vou aguardar a sua revisão e posterior aprovação e _merge_ da _Pull Request_ até pra entender bem o fluxo desse projeto antes de seguir contribuindo.
